services:
  mongodb:
    image: mongo:7.0
    container_name: mods-craft-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: modcraft2026
      MONGO_INITDB_DATABASE: mods-craft
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - mods-craft-network
    healthcheck:
      test: echo 'db.adminCommand("ping")' | mongosh -u admin -p modcraft2026 --authenticationDatabase admin
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mods-craft-mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: modcraft2026
      ME_CONFIG_MONGODB_URL: mongodb://admin:modcraft2026@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: modcraft2026
    depends_on:
      - mongodb
    networks:
      - mods-craft-network
    healthcheck:
      test: wget --quiet --tries=3 --spider http://localhost:8081 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  mongo-config:

networks:
  mods-craft-network:
    driver: bridge
